apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: weatherapp-weather
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weatherapp-weather
    spec:
      containers:
      - name: weatherapp-weather
        image: afakharany/weatherapp-weather:lab
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
        env:
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: apikey
                key: weather-apikey
        livenessProbe: 
          httpGet: 
            path: /
            port: http
        readinessProbe: 
          httpGet: 
            path: /
            port: http